# -*- coding: utf-8 -*-
"""aula5_programação_em_python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vHdbr7vW1Ww_HAKYzTFISC0C1Kl5FNyt
"""

#loop for
#serve para evitar retrabalhos
#evita digitar muitas vezes uma algoritmo

# print('olá mundo')
# print('olá mundo')
# print('olá mundo')
# print('olá mundo')
# print('olá mundo')

# print('------------------')

# for index in range(1,11):
#     print('ola mundo', index)





# lista ={1,3,6,89,78,15,56}
# palavras  =  'text'

# menino =  {
# 'nome':'Carlos',
# 'idade': 17,
# 'endereco': 'rua 10'
# }

# for a,b  in menino.items():
#     print(a,b)


# matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
# for linha in matriz:
#    for elemento in linha:
#        print(elemento)


# for i  in range(1,11,3):
#     print(i)


# print('1')
# for numero in range(2,21,2):
#     print(numero)

# print('2-------------')
# for n in range(5,50):
#     print(n, sum)

# print('-------------')
# soma =  sum(range(5,51,5))
# print(soma)


# n1 =  10
# n2 = type(n1)
# print(n2)

# words= 'hello world'
# r =  type(words)
# print(r)

# real  =  20.45
# result = type(real)
# print(result)


# name  =  input('Digite o nome')
# hello = 'Hello'
# print(hello+' ',name)


# for i  in range(1,11,2):
#     print(i)

soma  =  sum(range(1,11,2))
print(soma)

for n in range(1,11,2):
    print(n)